FROM python:3.9
RUN apt-get update
#RUN apt-get install gcc -y
WORKDIR /jobo
COPY jobo_bot.py NEAS.py scraping.py requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD [ "python", "jobo_bot.py" ]

